name: Go test package

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.20'

      - name: go mod tidy
        run: go mod tidy

      - name: Test
        run: go test -v ./...
